name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDJjMzdmMmMtNDc2ZC00OTY1LTgzNWItYTE0YjZmOTlmMDdiIiwidGVuYW50X2lkIjoiMDk3MzgwNjVkYzY3NzgyZmMzMWJjYTc3YjQ4OTkzODY3MDkzNDQ4M2I5ZWE2N2I5NjU5YTc5Y2Q1ZGU5Y2RkYiIsImludGVybmFsX3NlY3JldCI6ImVhZTRkNzhmLTcwYTgtNGMzNS1iYTU2LWM1NjRiMGM0YTU1MSJ9.LECHZpQJcX8naknUS-oBjEbdg3vdUSbTKncGZVzJl0U"
SECRET = "SECRET"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"